version: '3.9'
services:
  app:
    build: .
    image: app
    command: bash -c "
        ./manage.py migrate
        && ./manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app